version: '3.8'
services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: pagila
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    depends_on:
      - postgres
